name: CD

run-name: "[RELEASE] - Publish npm Packages"

permissions:
  contents: read
  actions: read
  packages: write

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  cd:
    uses: IronyxLabs/ironyx-scripts/.github/workflows/npm_package_cd-pipeline.yaml@v1
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
